##Folder path
#location: /home/yoseph/Desktop/fmf/
#spring:
#  application:
#    name: file-filtering
#    server:
#      port: 8081
#
#    spring:
#      security:
#        oauth2:
#          client:
#            registration:
#              client-id:
#                client-id: client-id
#                client-secret: client-secret
#                scope: openid,read
#                authorization-grant-type: authorization_code
#                redirect-uri: http://localhost:8081/login/oauth2/code/client-id
#            provider:
#              client-id:
#                issuer-uri: http://localhost:9000
